language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
before_script:
    - "pip install python-coveralls"
script:
    - "coverage run manage.py test debreach"
after_success:
    - "coveralls"
notifications:
    email: false
