language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
env:
    - DJANGO="django>=1.3,<1.4"
    - DJANGO="django>=1.4,<1.5"
    - DJANGO="django>=1.5,<1.6"
    - DJANGO="django>=1.6,<1.7"
    - DJANGO="https://www.djangoproject.com/download/1.7c1/tarball/"
install:
    - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install PyCrypto==2.3; else pip install PyCrypto; fi"
    - "pip install django${DJANGO}"
before_script:
    - "pip install python-coveralls coverage"
script:
    - "coverage run runtests.py"
after_success:
    - "coveralls"
notifications:
    email: false
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=">=1.3,<1.4"
    - python: "3.3"
      env: DJANGO=">=1.4,<1.5"
    - python: "3.4"
      env: DJANGO=">=1.3,<1.4"
    - python: "3.4"
      env: DJANGO=">=1.4,<1.5"
